name = "PCVCTRegistry"
uuid = "ac5acf56-370c-4ac8-b895-7453b15dc18b"
repo = "https://github.com/drbergman/PCVCTRegistry"

[packages]
3c374bc7-7384-4f83-8ca0-87b8c727e6ff = { name = "pcvct", path = "P/pcvct" }
