name = "PCVCTRegistry"
uuid = "ac5acf56-370c-4ac8-b895-7453b15dc18b"
repo = "https://github.com/drbergman/PCVCTRegistry"

[packages]
3c374bc7-7384-4f83-8ca0-87b8c727e6ff = { name = "pcvct", path = "P/pcvct" }
a4f5e88c-8ecf-4d3a-b1cd-9502f65e66f5 = { name = "PhysiCellECMCreator", path = "P/PhysiCellECMCreator" }
bad69253-e2d7-49f9-a0cf-2fd158c7c32b = { name = "PhysiCellXMLRules", path = "P/PhysiCellXMLRules" }
