name: Registry Consistency
on:
  - pull_request
  - push
  - workflow_dispatch
permissions:
  contents: read
jobs:
  check:
    name: Julia ${{ matrix.version }} on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.11'
          # - '1.12' # Uncomment this once Julia 1.12 is released
          # - 'nightly' # TODO: uncomment this line
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: julia-actions/setup-julia@9b79636afcfb07ab02c256cede01fe2db6ba808c # v2.6.0
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Cache artifacts and packages
        uses: julia-actions/cache@v2 # v2.0.5
      - run: julia --color=yes --project=.ci/ -e 'import Pkg; Pkg.precompile()'
      - run: julia --color=yes --project=.ci/ -e 'import RegistryCI; RegistryCI.test(registry_deps=["https://github.com/JuliaRegistries/General"])'
